project:
  type: book

book:
  title: "This is my thesis"
  author: "Susan Su"
  description: "A thesis submitted for the degree of Doctor of Philosophy at Monash University in 2023. Department of Econometrics & Business Statistics."
  chapters:
    - index.qmd
    - abstract.qmd
    - declaration.qmd
    - acknowledgements.qmd
    - "01-chap1.qmd"
    - "02-chap2.qmd"
  appendices:
    - "A-appA.qmd"
  references: refs.qmd
  page-footer:
    left: "Created using <a href='https://quarto.org'>Quarto</a>. © 2023, Susan Su"
    border: false
    background: light
  sidebar:
    background: "#cccccc"
    style: "docked"

toc-title: "<b>Sections</b>"
html-math-method: katex
published-title: "Last updated"
date-format: "DD MMMM YYYY"
number-depth: 2
bibliography: thesisrefs.bib
csl: apa-single-spaced.csl
fig-height: 3.8
fig-width: 6.3
degreetype: Doctor of Philosophy
submitted: 2023
affiliation: Department of Econometrics & Business Statistics
degrees: 'B.Sc. (Hons), University of Tangambalanga'
execute:
  freeze: auto
  echo: false

format:
  html:
    theme:
      - cosmo
      - thesis.scss
    fontsize: 16px
    mainfont: "Merriweather, Georgia, serif"
    code-link: true
  monashthesis-pdf:
    keep-tex: false
